# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build project
      run: zip --junk-paths EsnyaToolsAvatar3_0.zip .
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: zip
        GHR_PATH: EsnyaToolsAvatar3_0.zip
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
